# Generated by Django 4.1.1 on 2022-10-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_projects_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='techs',
            name='tech_pic',
            field=models.ImageField(blank=True, upload_to='photo/'),
        ),
    ]
